# Generated by Django 5.2.14 on 2026-05-25 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('ingestion_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.datasource')),
            ],
        ),
    ]
