# Generated by Django 5.2.14 on 2026-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_normalizedrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
