# Generated by Django 5.2.14 on 2026-05-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_normalizedrecord_is_locked'),
        ('tenants', '0002_tenantuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='data_quality_flag',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('MISSING_VALUES', 'Missing Values'), ('INVALID_ROW', 'Invalid Row'), ('SUSPICIOUS', 'Suspicious'), ('DUPLICATE', 'Duplicate')], default='CLEAN', max_length=20),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='normalization_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('NORMALIZED', 'Normalized'), ('FLAGGED', 'Flagged'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='workflow_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('NORMALIZED', 'Normalized'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='UNDER_REVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='tenants.tenant'),
        ),
    ]
