# Generated by Django 5.2.14 on 2026-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_normalizedrecord_data_quality_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='activity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='emission_unit',
            field=models.CharField(blank=True, default='kgCO2e', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='estimated_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='original_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='quality_score',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='suspicious_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='suspicious_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='validation_status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], default='WARNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawrecord',
            name='ingestion_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
    ]
