# Generated by Django 5.2.14 on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_normalizedrecord_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]