# Generated by Django 5.2.14 on 2026-05-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='uploaded_file',
            field=models.FileField(default='temp.csv', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
