# Generated by Django 5.2.14 on 2026-05-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_datasource_uploaded_file'),
        ('tenants', '0002_tenantuserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source_batches', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to='ingestion.datasourcebatch'),
        ),
    ]
