# Generated by Django 5.2.14 on 2026-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_datasourcebatch_datasource_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcebatch',
            name='reporting_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
