# Generated by Django 5.2.14 on 2026-05-28 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0004_normalizedrecord_data_quality_flag_and_more'),
        ('tenants', '0002_tenantuserprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOCK', 'Lock')], max_length=20, null=True)),
                ('performed_by', models.CharField(max_length=255)),
                ('user_role', models.CharField(blank=True, max_length=20, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason_for_change', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_changes', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='records.normalizedrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
        ),
    ]
