# Generated by Django 5.2.14 on 2026-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('REVIEW', 'Review'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOCK', 'Lock')], max_length=20, null=True),
        ),
    ]
